default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 10
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", "3306") %>
  username: <%= ENV.fetch("DB_USERNAME", "app") %>
  password: <%= ENV.fetch("DB_PASSWORD", "app_pass") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_development") %>

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_production") %>
  username: <%= ENV.fetch("DB_USERNAME", "app") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>